main.py
from datetime import timedelta
from flask import Flask, render_template
from routes.auth import auth
from routes.user import user

# app initialization
app = Flask(__name__)

# app config
app.config["SECRET_KEY"] = "64169bc491f8cb891fc0417d2eb29bb5"

# registered blueprints to app
app.register_blueprint(auth)
app.register_blueprint(user)

# session config
app.permanent_session_lifetime = timedelta(days=15)


# starting route / home route
@app.route('/')
def home():
    return render_template('home/home.html')


if __name__ == "__main__":
    app.run(debug=True)

routes/auth.py
from flask import Blueprint, render_template, request, session, flash
from models.auth.auth_forms import LoginForm, RegisterForm
from models.auth.auth_functions import *
from models.auth.account_classes import Customer

auth = Blueprint('auth', __name__)


@auth.route('/CustomerRegister', methods=["POST", "GET"])
def customer_register():
    error_messages = []
    register_form = RegisterForm()
    if not validate_username(register_form.username.data, relative_path_to_db='DB'):
        error_messages.append("Username is already taken, please use another one")
    if not validate_email(register_form.email.data, relative_path_to_db='DB'):
        error_messages.append("Email is already linked to an account, please use another one")
    if request.method == "POST" and register_form.validate():
        if validate_username(register_form.username.data, relative_path_to_db='DB') and validate_email(
                register_form.email.data, relative_path_to_db='DB'):
            customer = Customer(register_form.username.data, register_form.email.data, register_form.password1.data)
            store_customer(customer_object=customer, relative_path_to_db='DB')
            flash("You have successfully created a new account", category='success')
            return redirect(url_for('home'))
    else:
        for errors in register_form.errors.values():
            error_messages.append(errors[0])
    if error_messages:
        for message in error_messages:
            flash(message, category='danger')
    return render_template('auth/register.html', form=register_form)


@auth.route('/CustomerLogin', methods=["POST", "GET"])
def customer_login():
    login_form = LoginForm()
    if request.method == "POST":
        customer_dict = customer_login_authentication(login_form.username.data, login_form.password.data, 'DB')
        if customer_dict != {}:
            if login_form.remember.data:
                session.permanent = True
            else:
                session.permanent = False
            session['customer'] = customer_dict
            flash(f"Account {login_form.username.data} successfully logged in!", category="success")
            return redirect(url_for('user.customer_dashboard'))
        else:
            flash("Login failed! Please check your username or password again", category='danger')
    return render_template('auth/customer_login.html', form=login_form)


@auth.route('/StaffLogin', methods=["POST", "GET"])
def staff_login():
    login_form = LoginForm()
    if request.method == "POST":
        session['staff'] = login_form.username.data
        flash(f"Account {login_form.username.data} successfully logged in!", category="success")
        return redirect(url_for('user.staff_dashboard'))
    return render_template('auth/staff_login.html', form=login_form)


@auth.route('/logout')
def logout():
    if customer_login_required() or staff_login_required():
        session.pop('customer', None)
        session.pop('staff', None)
        flash("Account has been successfully logged out", category='info')
        return redirect(url_for('home'))
    else:
        restricted_customer_error()

routes/user.py
from flask import Blueprint, render_template

from models.auth.auth_functions import customer_login_required, restricted_customer_error, staff_login_required, \
    restricted_staff_error

user = Blueprint('user', __name__)


@user.route('/CustomerDashboard')
def customer_dashboard():
    if customer_login_required():
        return render_template('user/customer_dashboard.html')
    else:
        return restricted_customer_error()


@user.route('/StaffDashboard')
def staff_dashboard():
    if staff_login_required():
        return render_template('user/staff_dashboard.html')
    else:
        return restricted_staff_error()


@user.route('/customerProfile')
def customer_profile():
    if customer_login_required():
        return render_template('user/customer_profile.html')
    else:
        return restricted_customer_error()


@user.route('/StaffProfile')
def staff_profile():
    if staff_login_required():
        return render_template('user/staff_profile.html')
    else:
        return restricted_staff_error()

templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
 <!-- CSS only -->
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
    <title>
        {% block title %}
        {% endblock title %}
    </title>
  </head>

<body>
  <!-- Navbar -->
<nav class="navbar navbar-expand-lg navbar-dark bg-dark p-3">
      <div class="container-fluid">
        <a class="navbar-brand" href=" {{ url_for('home') }} ">Salon LOGO</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>

        <div class=" collapse navbar-collapse" id="navbarNavDropdown">
          <ul class="navbar-nav ms-auto ">
            <li class="nav-item">
              <a class="nav-link mx-2" aria-current="page" href=" {{ url_for('home') }} ">Home</a>
            </li>
            <li class="nav-item">
              <a class="nav-link mx-2" href="#">Shop</a>
            </li>
            <li class="nav-item">
              <a class="nav-link mx-2" href="#">Services</a>
            </li>
            <li class="nav-item">
              <a class="nav-link mx-2" href="#" id="navbarDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                About us
              </a>
            </li>
          </ul>
          <ul class="navbar-nav ms-auto justify-content-end">

            {% if 'customer' in session %}
            <li class="nav-item">
              <a class="nav-link mx-2" href="#"> 
                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-cart2" viewBox="0 0 16 16" style="color: white">
                  <path d="M0 2.5A.5.5 0 0 1 .5 2H2a.5.5 0 0 1 .485.379L2.89 4H14.5a.5.5 0 0 1 .485.621l-1.5 6A.5.5 0 0 1 13 11H4a.5.5 0 0 1-.485-.379L1.61 3H.5a.5.5 0 0 1-.5-.5zM3.14 5l1.25 5h8.22l1.25-5H3.14zM5 13a1 1 0 1 0 0 2 1 1 0 0 0 0-2zm-2 1a2 2 0 1 1 4 0 2 2 0 0 1-4 0zm9-1a1 1 0 1 0 0 2 1 1 0 0 0 0-2zm-2 1a2 2 0 1 1 4 0 2 2 0 0 1-4 0z"/>
                </svg>
              </a>
            </li>
            <li class="nav-item dropdown" style="margin-right: 20px">
              <a class="nav-link mx-2 dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-person-circle" viewBox="0 0 16 16" style="color: white">
                  <path d="M11 6a3 3 0 1 1-6 0 3 3 0 0 1 6 0z"/>
                  <path fill-rule="evenodd" d="M0 8a8 8 0 1 1 16 0A8 8 0 0 1 0 8zm8-7a7 7 0 0 0-5.468 11.37C3.242 11.226 4.805 10 8 10s4.757 1.225 5.468 2.37A7 7 0 0 0 8 1z"/>
                </svg>
              </a>
              <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink" style="min-width: 10px;">
                <li><a class="dropdown-item"href=" {{url_for('user.customer_dashboard')}} ">Dashboard </a></li>
                <li><a class="dropdown-item"href=" {{url_for('user.customer_profile')}} ">Profile</a></li>
                <li><hr class="dropdown-divider" /></li>
                <li><a class="dropdown-item" href="{{ url_for('auth.logout') }} ">Logout</a></li>
              </ul>
            </li>
            {% elif 'staff' in session %}

            {% else %}
            <li class="nav-item">
              <a class="nav-link mx-2" href="{{ url_for('auth.customer_register') }}"> Register </a>
            </li>
            <li class="nav-item dropdown">
              <a class="nav-link mx-2 dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                Login
              </a>
              <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink" style="min-width: 25px;">
                <li><a class="dropdown-item" href=" {{ url_for('auth.customer_login') }} ">Customer</a></li>
                <li><hr class="dropdown-divider" /></li>
                <li><a class="dropdown-item" href="{{ url_for('auth.staff_login') }} ">Staff</a></li>
              </ul>
            </li>

            {% endif %}

              </ul>
        </div>
      </div>
    </nav>
{% with messages = get_flashed_messages(with_categories=True) %}
    {% for category, message in messages %}
      <div class="alert alert-{{category}} alert-dismissible fade show =" role="alert">
        {% if category == "danger" %}
        <strong>Warning!</strong>
        {% elif category == "success" %}
        <strong>Success!</strong>
        {% elif category == "info" %}
        <strong>Info</strong>
        {% endif %}
        {{ message }}
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
      </div>
    {% endfor %}
{% endwith %}

{% block content %}
{% endblock content %}

<!-- JavaScript Bundle with Popper -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous"></script>

  </body>
</html>

templates/home/home.html
{% extends 'base.html' %}

{% block title %}
Home Page
{% endblock title %}

{% block content %}
<h1>Home page Welcome</h1>
{% endblock content %}

templates/user/customer_dashboard.html
{% extends 'base.html' %}

{% block title %}
Customer Profile
{% endblock title %}

{% block content %}
<h1>Welcome Customer {{ session["customer"]["_User__username"] }}. This is your dashboard</h1>
{% endblock content %}

templates/user/staff_dashboard.html
{% extends 'base.html' %}

{% block title %}
Staff profile
{% endblock title %}

{% block content %}
<h1>Welcome Staff {{ session["staff"] }}</h1>
{% endblock content %}

templates/user/staff_profile.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>